name: Run Test Suite

on: push

jobs:
  run-test-suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8]
        django_version: [2.2, 3.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: pip install -r requirements_test.txt

      - name: Run Tests
        run: tox -e py${{ matrix.python_version }}-django${{ matrix.django_version }}

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
